[colors.primary]
background = "#191724"
foreground = "#e0def4"
dim_foreground = "#aaa8b9"
bright_foreground = "#eae8ff"

[colors.cursor]
text = "#191724"
cursor = "#e0def4"

[colors.selection]
text = "#e0def4"
background = "#403d52"

[colors.normal]
black = "#26233a"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"

[colors.bright]
black = "#6e6a86"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"

[colors.dim]
black = "#484559"
red = "#ee85a3"
green = "#518aa0"
yellow = "#f7cb8c"
blue = "#abd6de"
magenta = "#cdb5eb"
cyan = "#eec6c5"
white = "#e5e3f6"

[[colors.indexed_colors]]
index = 16
color = "#f19885"

[[colors.indexed_colors]]
index = 17
color = "#e6a7c3"

[font.normal]
family = "ZedMono Nerd Font Mono"

[cursor.style]
shape = "Block"

[window]
dynamic_padding = true

[window.padding]
x = 6
y = 6
