[colors.primary]
background = "#101010"
foreground = "#e0e1e4"
dim_foreground = "#a6a7a9"
bright_foreground = "#eff0f3"

[colors.cursor]
text = "#18191b"
cursor = "#e0e1e4"

[colors.selection]
text = "#e0e1e4"
background = "#696d79"

[colors.normal]
black = "#151515"
red = "#b46958"
green = "#90a959"
yellow = "#f4bf75"
blue = "#bad7ff"
magenta = "#aa759f"
cyan = "#88afa2"
white = "#e1e1e1"

[colors.bright]
black = "#727272"
red = "#7e97ab"
green = "#90a959"
yellow = "#f4bf75"
blue = "#bad7ff"
magenta = "#aa759f"
cyan = "#88afa2"
white = "#afafaf"

[colors.dim]
black = "#393939"
red = "#c08072"
green = "#a1b673"
yellow = "#f6c98a"
blue = "#c5ddff"
magenta = "#b78aae"
cyan = "#9abbb0"
white = "#e6e6e6"

[[colors.indexed_colors]]
index = 16
color = "#d49467"

[[colors.indexed_colors]]
index = 17
color = "#cba59d"

[font.normal]
family = "ZedMono Nerd Font Mono"

[cursor.style]
shape = "Block"

[window]
dynamic_padding = true

[window.padding]
x = 6
y = 6
